### ISSUE TITLE
Features & requirements

### ISSUE THREAD

**Issue by igrigorik** [mikewest/error-reporting#2]
A braindump, in no particular order... 

We want to define a mechanism that the UA can use to deliver out-of-band reports about security violations, performance issues, failed loads, etc. That is, we're not restricted to "errors". 
- The origin needs to be able to register a persistent policy with one or more report-URI's (see [NEL]())
  - The policy should have a max-age
  - max-age: 0 should unregister the policy
  - The policy should have a subdomain opt-in
  - All reporting URIs should be validated: `"` delimited absolute URI's and https-only.
  - I believe we can lift much of the above from https://w3c.github.io/network-error-logging/#the-report-uri-directive and https://w3c.github.io/network-error-logging/#policy-storage-and-maintenance
- It would be nice if the origin could register _multiple_ policies with alternate sets of report-uri's...
  - Each policy set has a unique ID that can be set by the origin; if ID is omitted we assign report-uri's to the 'default' policy set - e.g. `Reporting: "https://a.com" "https://b.com"; id=stuff; includeSubdomains; max-age=51920000, "https://c.com"; id=other; max-age: 5192000`.
  - This allows reports to be targeted at specific sets of report-URI's -- e.g. diagnostics reports go here, security violations go there, and so on.
-  We should restrict this entire future to HTTPS origins -- some of the reports may contain data that's not otherwise available.
- Define interactive with serviceworker (treat as client request) - see https://github.com/w3c/network-error-logging/issues/54.
- For reporting...
  - Define failover mechanism: iterate in order for provided set of report-uri's and attempt delivery.
  - Stop on 200, remove registered report-uri on 410.
  - Provide some clause about retries and backoff; provide a mechanism for Retry-After - see https://github.com/w3c/network-error-logging/issues/32.
  - When the report is queued by the UA we should probably provide a few configuration bits for delivery policy: best effort vs retry vs ...
  - Add some logic for rate-limiting and aggregation on the UA - e.g. deliver multiple reports in same request
  - Add logic to garbage-collect bad report-URIs - e.g. if delivery fails x times, remove it from the set of report-uri's.
  - Add logic to detect loops: delivery of report triggers another report.. We should probably fail on any/every network error and skip redirects.
- Define report structure / JSON blob: {..., reports: [ ... ] } 
  - Each report under `reports` should have an `age` field that reports how long the report was sitting on the client before it was queued for delivery (important for real-time stats and alerting use cases).

There's probably lots more, but this is a start.. FWIW, NEL already tackles a good subset of the above, and we can probably lift a lot out of it: https://w3c.github.io/network-error-logging/

Also, for reference:  https://docs.google.com/document/d/19HgJ66W8CIloI3TQsMGPfIPdkl6UXtRtXT5P_m4RCj0/edit

**Comment by mikewest** [comment]
You almost scared me away with this, but not quite. I've started poking at the spec again, and it would be lovely if you could take a stab at some bits as well. Maybe we can get a draft together before TPAC? That would be nice.

**Comment by igrigorik** [comment]
@mikewest sounds like a plan. I'll try to move some of the NEL bits either tomorrow or thursday.

**Comment by mikewest** [comment]
Done, yes?

**Comment by igrigorik** [comment]
:+1:
