### ISSUE TITLE
Header syntax

### ISSUE THREAD

**Issue by mnot** [mikewest/error-reporting#4]
We should talk about it.

**Comment by mnot** [comment]
Specifically, URLs should be in quotes because they can contain commas and semicolons.

See also:
  http://httpwg.github.io/specs/rfc7231.html#considerations.for.new.header.fields

Also, @reschke should look at the ABNF.

Spec:
  http://mikewest.github.io/error-reporting/#header

**Comment by reschke** [comment]
We can do this again and again and again, or we could switch to a standard syntax for new fields (-> http://greenbytes.de/tech/webdav/draft-reschke-http-jfv-02.html)

**Comment by mnot** [comment]
It has to become a standard first... hmm, if only someone could do that...

**Comment by reschke** [comment]
Do you want to put it on the WG agenda?

**Comment by mnot** [comment]
Yes.

**Comment by igrigorik** [comment]
If jfv is 'blessed' as the path forward for all HTTP headers, I'm open to exploring it as an option here, but at the same time I'm wary of blazing the path with it...

**Comment by mikewest** [comment]
I've decided not to be wary. Let's see how it goes: https://github.com/w3c/reporting/commit/64c724c426c7d464c93e6a31d83d0d0debec6080.

Closing out this bug, let's discuss it on that other repository if I've done things terribly. :)
